config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names:
                 {
                   sign_in: 'login',
                   sign_out: 'logout',
                   edit: 'profile'
                 },
             controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :users, only: :show
  resources :rooms, path: 'annonces' do
    resources :reservations, only: :create
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos
  resources :conversations, only: [:create, :index] do
    resources :messages, only: [:create, :index]
  end
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/mes_voyages' => 'reservations#your_trips', as: 'mes_voyages'
  get '/mes_reservations' => 'reservations#your_reservations', as: 'mes_reservations'
  get '/search' => 'pages#search'
end

app/views/layouts/_navigation.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'clone Airbnb', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: 'navbar-form navbar-left', method: :get do %>
        <div class="search">
          <span class="fa fa-search"></span>
          <%= text_field_tag :search, params[:search], placeholder: 'Rechercher', class: 'form-control' %>
        </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_room_path do %>
            <i class="fa fa-home fa-lg"></i> Devenez hôte
          <% end %>
        </li>
        <% unless user_signed_in? %>
          <li><%= link_to 'Inscription', new_user_registration_path %></li>
          <li><%= link_to 'Identification', new_user_session_path %></li>
        <% else %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: 'img-circle avatar-small' %><%= current_user.fullname %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Mes annonces', rooms_path %></li>
              <li><%= link_to 'Mes voyages', mes_voyages_path %></li>
              <li><%= link_to 'Mes réservations', mes_reservations_path %></li>
              <li><%= link_to 'Modifier son profil', edit_user_registration_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>

            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clone Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/message' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>